project:
  type: book

book:
  title: "3301"
  site-url: https://adv-gis-rs.github.io/
  author: "John Duncan and Bryan Boruff"
  chapters:
    - href: index.qmd
      text: Home
    - href: js-introduction.qmd
      text: JavaScript
    - href: ee-introduction.qmd
      text: GEE Introduction
    - href: colour-vis.qmd
      text: Color and Data Visualisation
    # - href: vector.qmd
    #   text: Vector Data Operations
    # - href: raster-image.qmd
    #   text: Raster Data Operations
    # - href: lab-7.qmd
    #   text: Lab 8
    # - href: lab-8.qmd
    #   text: Lab 9
    # - href: lab-9.qmd
    #   text: Lab 10


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    number-sections: false
  pdf:
    documentclass: scrreprt



